final List<Map<String, dynamic>> books = [
  {
    'ad': '1984',
    'yazar': 'George Orwell',
    'gorsel': 'assets/images/books/1984.jpg',
    'aciklama': 'George Orwell\'in en çarpıcı eserlerinden biri olan "1984", baskıcı bir rejim altında yaşayan bireylerin hayatını konu alır. Kitap, totaliter bir rejimin insanları nasıl manipüle ettiğini, özgürlüğü nasıl bastırdığını ve gerçeği nasıl çarpıttığını etkileyici bir dille anlatır. Büyük Birader\'in gölgesinde geçen bu distopik roman, bireysel özgürlüklerin ve düşünce özgürlüğünün önemine dair derin mesajlar içerir.',
    'durum': 1,
  },
  {
    'ad': 'Sefiller',
    'yazar': 'Victor Hugo',
    'gorsel': 'assets/images/books/sefiller.jpg',
    'aciklama': 'Victor Hugo\'nun klasik eseri "Sefiller", Fransız Devrimi sırasında geçen dramatik bir hikâyeyi anlatır. Jean Valjean\'ın topluma yeniden karışma çabaları ve adaletle olan mücadelesi, insan doğasının karmaşıklığını ve merhametin gücünü ortaya koyar. Eserde, aşk, fedakârlık ve adalet temaları, tarihi bir arka planla birlikte usta bir şekilde işlenmiştir.',
    'durum': 2,
  },
  {
    'ad': 'Dönüşüm',
    'yazar': 'Franz Kafka',
    'gorsel': 'assets/images/books/donusum.jpg',
    'aciklama': 'Franz Kafka\'nın ikonik eseri "Dönüşüm", bir sabah kendini devasa bir böcek olarak bulan Gregor Samsa\'nın trajik ve absürd hikâyesini anlatır. Kafka, insan ilişkilerindeki yabancılaşmayı, bireyin toplumdaki yerini ve varoluşsal sıkıntıları alegorik bir dille ele alır. Bu eser, modern edebiyatın en etkileyici örneklerinden biridir ve insan ruhunun derinliklerine ışık tutar.',
    'durum': 1,
  },
  {
    'ad': 'Suç ve Ceza',
    'yazar': 'Fyodor Dostoyevski',
    'gorsel': 'assets/images/books/sucveceza.jpg',
    'aciklama': 'Fyodor Dostoyevski\'nin başyapıtlarından biri olan "Suç ve Ceza", Rusya\'nın Petersburg şehrinde geçen, ahlaki ikilemlerle dolu bir cinayet ve sonrasındaki vicdan muhasebesini konu alır. Raskolnikov, işlediği cinayetle birlikte, kendi vicdanıyla savaşmaya başlar. Eserde, insanın içsel çatışmalarını ve toplumsal adalet anlayışını sorgulayan derin bir felsefi analiz bulunur.',
    'durum': 2,
  },
  {
    'ad': 'Uçurtma Avcısı',
    'yazar': 'Khaled Hosseini',
    'gorsel': 'assets/images/books/ucturtmavcisi.jpg',
    'aciklama': 'Khaled Hosseini\'nin "Uçurtma Avcısı", Afganistan\'ın tarihsel arka planında gelişen iki arkadaşın dramını anlatır. Kitap, dostluk, ihanet, suçluluk ve kefaret temalarını işler. Amr ve Hassan arasındaki ilişkinin, Afgan toplumunun değişimi ve Sovyet işgaliyle birlikte nasıl etkilendiği duygusal bir dille aktarılır.',
    'durum': 1,
  },
  {
    'ad': 'Yüzüklerin Efendisi',
    'yazar': 'J.R.R. Tolkien',
    'gorsel': 'assets/images/books/yuzuklerinefendisi.jpg',
    'aciklama': 'J.R.R. Tolkien\'in epik fantastik eseri "Yüzüklerin Efendisi", Orta Dünya\'da geçen, iyilik ve kötülüğün savaşı üzerinde yoğunlaşan bir hikâyedir. Frodo Baggins ve arkadaşları, gücü kötüye kullanmaya çalışan Sauron\'a karşı mücadele verir. Eser, fantastik edebiyatın en önemli yapıtlarından biri olarak kabul edilir.',
    'durum': 2,
  },
  {
    'ad': 'Moby Dick',
    'yazar': 'Herman Melville',
    'gorsel': 'assets/images/books/mobydick.jpg',
    'aciklama': 'Herman Melville\'in "Moby Dick" adlı romanı, denizcilerin büyük beyaz balina Moby Dick’i avlama çabalarını ve bu yolculuğun insan ruhu üzerindeki etkilerini konu alır. Kaptan Ahab’ın takıntılı intikamı, insanın doğa ve kader karşısındaki zaafiyetini derinlemesine keşfeder.',
    'durum': 1,
  },
  {
    'ad': 'Savaş ve Barış',
    'yazar': 'Lev Tolstoy',
    'gorsel': 'assets/images/books/savasvebaris.jpg',
    'aciklama': 'Lev Tolstoy\'un başyapıtı "Savaş ve Barış", Napolyon Savaşları sırasında Rusya\'da yaşayan aristokratların hayatlarını ve savaşın etkilerini anlatan bir romandır. Eser, bireysel kader ile tarihsel olaylar arasındaki ilişkiyi derinlemesine inceleyerek, insanlık durumunu kapsamlı bir şekilde ele alır.',
    'durum': 2,
  },
  {
    'ad': 'Anna Karenina',
    'yazar': 'Lev Tolstoy',
    'gorsel': 'assets/images/books/annakarenina.jpg',
    'aciklama': 'Lev Tolstoy\'un "Anna Karenina" adlı eseri, aristokrat bir kadının aşk, sadakat ve toplumun baskılarıyla mücadelesini anlatır. Anna\'nın trajik hikâyesi, toplumsal normlarla bireysel özgürlük arasındaki çatışmayı derinlemesine keşfeder.',
    'durum': 1,
  },
  {
    'ad': 'Küçük Prens',
    'yazar': 'Antoine de Saint-Exupéry',
    'gorsel': 'assets/images/books/kucukprens.jpg',
    'aciklama': 'Antoine de Saint-Exupéry\'nin "Küçük Prens" adlı eseri, büyüklere hitap eden bir masaldır. Bir uçak kazasında çöle düşen bir pilot, orada karşılaştığı Küçük Prens\'in hikâyesini anlatır. Kitap, sevgi, dostluk, hayatın anlamı ve çocukluğun saflığı üzerine derin felsefi mesajlar içerir.',
    'durum': 2,
  },
  {
    'ad': 'İçimizdeki Şeytan',
    'yazar': 'Sabahattin Ali',
    'gorsel': 'assets/images/books/icimizdekiseytan.jpg',
    'aciklama': 'Sabahattin Ali\'nin "İçimizdeki Şeytan" adlı eseri, bireyin içsel çatışmaları ve toplumsal baskılarla mücadelesini işler. Eserde, aşk, yalnızlık ve toplumla uyumsuzluk temaları yoğun bir şekilde ele alınır.',
    'durum': 1,
  },
  {
    'ad': 'Fahrenheit 451',
    'yazar': 'Ray Bradbury',
    'gorsel': 'assets/images/books/fahrenheit451.jpg',
    'aciklama': 'Ray Bradbury\'nin "Fahrenheit 451" adlı distopik romanı, kitapların yasaklandığı ve insanların yalnızca devletin doğru bulduğu bilgileri okuduğu bir geleceği anlatır. Kitap, bireysel özgürlükler ve toplumun baskısı üzerine derinlemesine bir sorgulama yapar.',
    'durum': 2,
  },
  {
    'ad': 'Hayvan Çiftliği',
    'yazar': 'George Orwell',
    'gorsel': 'assets/images/books/hayvanciftligi.jpg',
    'aciklama': 'George Orwell\'in "Hayvan Çiftliği", Sovyetler Birliği\'ndeki totaliter rejimi eleştiren alegorik bir eserdir. Kitap, çiftlikteki hayvanların, zalim bir yöneticiye karşı başlattıkları isyanı ve sonrasında iktidarın nasıl yozlaştığını anlatır.',
    'durum': 1,
  },
  {
    'ad': 'Germinal',
    'yazar': 'Émile Zola',
    'gorsel': 'assets/images/books/germinal.jpg',
    'aciklama': 'Émile Zola\'nın "Germinal" adlı eseri, Fransa\'daki madenci işçilerin yaşadığı zorlukları ve hak mücadelesini anlatır. Eser, işçi sınıfının mücadelelerini ve kapitalist düzenin sömürücü doğasını vurgular.',
    'durum': 2,
  },
  {
    'ad': 'Karamazov Kardeşler',
    'yazar': 'Fyodor Dostoyevski',
    'gorsel': 'assets/images/books/karamazovkardesler.jpg',
    'aciklama': 'Fyodor Dostoyevski\'nin "Karamazov Kardeşler" adlı eseri, üç kardeşin, babalarının katili olduklarını iddia eden bir olayın ardından gelişen karmaşık duygusal ve ahlaki bir çatışmayı anlatır. Kitap, ahlak, din ve insan doğasının derinliklerini sorgular.',
    'durum': 1,
  },
  {
    'ad': 'Zorba',
    'yazar': 'Nikos Kazancakis',
    'gorsel': 'assets/images/books/zorba.jpg',
    'aciklama': 'Nikos Kazancakis\'in "Zorba" adlı eseri, Yunanistan\'da geçen, hayatı dolu dolu yaşayan bir adam olan Zorba\'nın hikâyesini anlatır. Kitap, yaşamın anlamını, insanın tutkularını ve özgürlüğünü sorgular.',
    'durum': 2,
  },
  {
    'ad': 'Büyük Umutlar',
    'yazar': 'Charles Dickens',
    'gorsel': 'assets/images/books/buyukumutlar.jpg',
    'aciklama': 'Charles Dickens\'ın "Büyük Umutlar" adlı eseri, genç Pip\'in hayatındaki değişimi ve büyüme sürecini konu alır. Pip, büyük bir servet kazanma umudu ile yola çıkar ancak hayat ona farklı dersler öğretir.',
    'durum': 1,
  },
];

